using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;

// ==========================================
// 1. THE DATA MODEL (Backend Logic)
// This code has NO dependency on the GUI.
// ==========================================

namespace AwsDesigner.Core
{
    // Enum for resource types
    public enum ResourceType { EC2_Instance, S3_Bucket, SNS_Topic }

    // Represents a single block on your diagram
    public abstract class AwsNode
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string Name { get; set; }
        public double X { get; set; } // Position for the GUI to read/write
        public double Y { get; set; }
        
        public abstract string GetCloudFormationType();
        public abstract Dictionary<string, object> GetProperties();
    }

    public class Ec2Node : AwsNode
    {
        public string InstanceType { get; set; } = "t2.micro";
        public string ImageId { get; set; } = "ami-0abcdef1234567890";

        public override string GetCloudFormationType() => "AWS::EC2::Instance";

        public override Dictionary<string, object> GetProperties()
        {
            return new Dictionary<string, object>
            {
                { "InstanceType", InstanceType },
                { "ImageId", ImageId },
                // Tags could go here
            };
        }
    }

    public class S3Node : AwsNode
    {
        public string BucketName { get; set; }

        public override string GetCloudFormationType() => "AWS::S3::Bucket";

        public override Dictionary<string, object> GetProperties()
        {
            return new Dictionary<string, object>
            {
                { "BucketName", BucketName }
            };
        }
    }

    // Represents a line drawn between two nodes
    public class Connection
    {
        public string SourceNodeId { get; set; }
        public string TargetNodeId { get; set; }
        
        // e.g., "Permissions", "NetworkFlow", "Logging"
        public string ConnectionType { get; set; } 
    }

    // The entire diagram state
    public class DesignerGraph
    {
        public List<AwsNode> Nodes { get; set; } = new List<AwsNode>();
        public List<Connection> Connections { get; set; } = new List<Connection>();
    }

    // ==========================================
    // 2. THE GENERATOR (The "Execute" Button)
    // ==========================================

    public class CloudFormationGenerator
    {
        public string GenerateTemplate(DesignerGraph graph)
        {
            var resources = new Dictionary<string, object>();

            // 1. Create Resources
            foreach (var node in graph.Nodes)
            {
                // Clean name for logical ID (remove spaces, etc)
                string logicalId = node.Name.Replace(" ", "") + node.Id.Substring(0, 4);

                var resourceDef = new
                {
                    Type = node.GetCloudFormationType(),
                    Properties = node.GetProperties()
                };

                resources.Add(logicalId, resourceDef);

                // 2. Handle Connections (Implicit Logic)
                // Example: If EC2 is connected to S3, add an IAM InstanceProfile 
                // to the EC2 definition allowing access to that S3 bucket.
                var outgoingConnections = graph.Connections.Where(c => c.SourceNodeId == node.Id);
                foreach (var conn in outgoingConnections)
                {
                    var target = graph.Nodes.FirstOrDefault(n => n.Id == conn.TargetNodeId);
                    if (target is S3Node)
                    {
                        Console.WriteLine($"[Logic] Detected connection from {node.Name} to {target.Name}. Injecting IAM Role...");
                        // In a real app, you would add a 'DependsOn' or 'IamInstanceProfile' property here
                    }
                }
            }

            var template = new
            {
                AWSTemplateFormatVersion = "2010-09-09",
                Description = "Generated by C# AwsDesigner",
                Resources = resources
            };

            return JsonSerializer.Serialize(template, new JsonSerializerOptions { WriteIndented = true });
        }
    }

    // ==========================================
    // 3. USAGE EXAMPLE (How the GUI calls this)
    // ==========================================
    public class Program
    {
        public static void Main()
        {
            // --- SIMULATING THE GUI ---
            
            // 1. User drags an EC2 instance onto the canvas
            var ec2 = new Ec2Node { Name = "My Web Server", X = 100, Y = 100 };
            
            // 2. User drags an S3 bucket
            var s3 = new S3Node { Name = "Assets Bucket", BucketName = "my-app-assets-123", X = 400, Y = 150 };

            // 3. User draws a line from EC2 to S3
            var connection = new Connection { SourceNodeId = ec2.Id, TargetNodeId = s3.Id };

            // 4. The Graph stores this state
            var graph = new DesignerGraph();
            graph.Nodes.Add(ec2);
            graph.Nodes.Add(s3);
            graph.Connections.Add(connection);

            // --- EXECUTING THE COMMAND ---

            Console.WriteLine("User clicked 'Execute'. Generating Infrastructure...");
            
            var generator = new CloudFormationGenerator();
            string jsonTemplate = generator.GenerateTemplate(graph);

            Console.WriteLine("\n--- Generated CloudFormation Template ---");
            Console.WriteLine(jsonTemplate);
            
            // 5. In the real app, you would now use Amazon.CloudFormation.Model.CreateStackRequest
            // var cfClient = new AmazonCloudFormationClient();
            // await cfClient.CreateStackAsync(...);
        }
    }
}